name: CI Check
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and START
        run: |
          # Собираем и ЗАПУСКАЕМ в фоновом режиме (-d)
          docker compose up -d 

      - name: Test Infrastructure
        run: |
          # Даем контейнерам время проснуться
          sleep 15
          # Смотрим логи, если что-то пойдет не так (поможет при отладке)
          docker compose logs backend
          # Теперь curl точно найдет запущенный сервер
          curl -f http://localhost:8080/health || exit 1


