name: CI Check
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Check
        run: docker compose build

      # Добавим запуск и проверку (опционально, когда будешь готов)
      - name: Test Infrastructure
        run: |
          # Даем контейнерам 10 секунд, чтобы они успели запуститься
          sleep 10
          curl -f http://localhost:8080/health || exit 1 

