name: CI Check
on:
  push:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Check
        run: docker compose build

      # Добавим запуск и проверку (опционально, когда будешь готов)
      - name: Test Infrastructure
        run: |
          docker compose up -d
          sleep 5
          # Проверяем, что наш health-эндпоинт отвечает 200 OK
          curl -f http://localhost:8080/health || exit 1
          docker compose down 

